import re
import os
from typing import List, Dict, Any, Optional
from decimal import Decimal
from app.services.ai_buyer_interface import AIBuyerAdapter


class LLMAIBuyerAdapter(AIBuyerAdapter):
    """
    Interface wrapper for LLM-assisted AI Buyers (e.g. OpenAI / Anthropic / Gemini).
    
    IMPORTANT SECURITY INVARIANT:
    All output generated by the LLM is treated as UNTRUSTED client input.
    The LLM NEVER decides payment authorization or ALLOW/BLOCK outcomes.
    All LLM outputs pass through standard Pydantic schemas and IntentLock's 21-check
    deterministic verification engine.
    """

    def __init__(self, api_key: Optional[str] = None, model_name: str = "gpt-4o"):
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        self.model_name = model_name

    def parse_user_prompt(self, prompt: str) -> Dict[str, Any]:
        """
        Extract intent requirements (action, quantity, max_amount, search_query) from prompt text.
        Falls back to regex heuristics if external LLM API is unconfigured.
        """
        # Parse currency/amount e.g. "under ₹1500" or "under 1500" or "INR 1500"
        amount_match = re.search(r'(?:under|below|max|for|limit|budget|₹|INR|\$)\s*(?:₹|INR|\$)?\s*(\d+(?:\.\d{1,2})?)', prompt, re.IGNORECASE)
        max_amount = Decimal(amount_match.group(1)) if amount_match else Decimal("1000.00")
        
        # Parse item quantity e.g. "Buy 2", "2 items"
        qty_match = re.search(r'\b(?:buy|purchase|quantity|qty)?\s*(\d+)\s*(?:items|units|pcs|gaming|headsets|mice|mouse|products)?\b', prompt, re.IGNORECASE)
        quantity = int(qty_match.group(1)) if (qty_match and Decimal(qty_match.group(1)) != max_amount) else 1
        
        # Parse search query keywords
        query_words = [w for w in prompt.split() if w.lower() not in ("buy", "one", "a", "an", "under", "for", "please", "purchase", "the")]
        search_query = " ".join(query_words) if query_words else prompt

        return {
            "action": "PURCHASE",
            "quantity": quantity,
            "max_amount": max_amount,
            "search_query": search_query
        }

    def discover_products(
        self, client: Any, query: str, max_price: Optional[Decimal] = None
    ) -> List[Dict[str, Any]]:
        params = {"q": query}
        if max_price is not None:
            params["max_price"] = str(max_price)
        res = client.get("/catalog/products", params=params)
        if res.status_code == 200:
            return res.json()
        return []

    def select_product(
        self, query: str, catalog: List[Dict[str, Any]]
    ) -> Optional[Dict[str, Any]]:
        if not catalog:
            return None
        # LLM reasoning selects best matching catalog entry
        for item in catalog:
            if item.get("is_available", True):
                return item
        return catalog[0]

    def generate_proposal(
        self, client: Any, intent_id: str, product_id: str, quantity: int = 1
    ) -> Dict[str, Any]:
        res = client.post(
            "/intent/workflow/proposal",
            json={
                "intent_id": intent_id,
                "product_id": product_id,
                "quantity": quantity
            }
        )
        if res.status_code in (200, 201):
            return res.json()
        raise ValueError(f"LLM proposal generation failed: {res.text}")

    def construct_transaction(
        self,
        authorization_id: str,
        agent_id: str,
        merchant_id: str,
        product_id: str,
        amount: Decimal,
        quantity: int = 1,
        currency: str = "INR",
        add_ons: Optional[str] = None
    ) -> Dict[str, Any]:
        return {
            "authorization_id": authorization_id,
            "agent_id": agent_id,
            "merchant_id": merchant_id,
            "product_id": product_id,
            "requested_amount": str(amount),
            "quantity": quantity,
            "currency": currency,
            "add_ons": add_ons
        }
