import re
import os
from typing import List, Dict, Any, Optional
from decimal import Decimal
from app.services.ai_buyer_interface import AIBuyerAdapter


class LLMAIBuyerAdapter(AIBuyerAdapter):
    """
    Interface wrapper for LLM-assisted AI Buyers (e.g. OpenAI / Anthropic / Gemini).
    
    IMPORTANT SECURITY INVARIANT:
    All output generated by the LLM is treated as UNTRUSTED client input.
    The LLM NEVER decides payment authorization or ALLOW/BLOCK outcomes.
    All LLM outputs pass through standard Pydantic schemas and IntentLock's 21-check
    deterministic verification engine.
    """

    def __init__(self, api_key: Optional[str] = None, model_name: str = "gpt-4o"):
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        self.model_name = model_name

    def parse_user_prompt(self, prompt: str) -> Dict[str, Any]:
        """
        Extract intent requirements (action, quantity, max_amount, search_query) from prompt text.
        Delegates to LLMSemanticParser for structured Pydantic schema validation.
        """
        from app.services.llm_semantic_parser import LLMSemanticParser
        parser = LLMSemanticParser(api_key=self.api_key, model_name=self.model_name)
        parsed_bound = parser.parse(prompt)

        return {
            "action": parsed_bound.action,
            "quantity": parsed_bound.quantity,
            "max_amount": parsed_bound.max_amount,
            "search_query": parsed_bound.product_query,
            "intent_status": parsed_bound.intent_status,
        }

    def discover_products(
        self, client: Any, query: str, max_price: Optional[Decimal] = None
    ) -> List[Dict[str, Any]]:
        params = {"q": query}
        if max_price is not None:
            params["max_price"] = str(max_price)
        res = client.get("/catalog/products", params=params)
        if res.status_code == 200:
            return res.json()
        return []

    def select_product(
        self, query: str, catalog: List[Dict[str, Any]]
    ) -> Optional[Dict[str, Any]]:
        if not catalog:
            return None
        # LLM reasoning selects best matching catalog entry
        for item in catalog:
            if item.get("is_available", True):
                return item
        return catalog[0]

    def generate_proposal(
        self, client: Any, intent_id: str, product_id: str, quantity: int = 1
    ) -> Dict[str, Any]:
        res = client.post(
            "/intent/workflow/proposal",
            json={
                "intent_id": intent_id,
                "product_id": product_id,
                "quantity": quantity
            }
        )
        if res.status_code in (200, 201):
            return res.json()
        raise ValueError(f"LLM proposal generation failed: {res.text}")

    def construct_transaction(
        self,
        authorization_id: str,
        agent_id: str,
        merchant_id: str,
        product_id: str,
        amount: Decimal,
        quantity: int = 1,
        currency: str = "INR",
        add_ons: Optional[str] = None
    ) -> Dict[str, Any]:
        return {
            "authorization_id": authorization_id,
            "agent_id": agent_id,
            "merchant_id": merchant_id,
            "product_id": product_id,
            "requested_amount": str(amount),
            "quantity": quantity,
            "currency": currency,
            "add_ons": add_ons
        }
